# Generated by Django 6.0.4 on 2026-05-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="createdAt"),
                ),
                (
                    "updatedAt",
                    models.DateTimeField(auto_now=True, verbose_name="updatedAt"),
                ),
                ("name", models.CharField(max_length=50)),
                ("length", models.IntegerField()),
                ("configuration", models.CharField(default="n/a", max_length=50)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
