# Generated by Django 6.0.4 on 2026-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="track",
            constraint=models.UniqueConstraint(fields=("name",), name="unique_name"),
        ),
    ]
