# Generated by Django 6.0.4 on 2026-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_track_unique_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="length",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
