# Generated by Django 6.0.4 on 2026-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0003_alter_track_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="track",
            name="state",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
