# Generated by Django 6.0.4 on 2026-05-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0004_track_city_track_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="short_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
